// <auto-generated />
using System;
using Acquisition.Api.Infrastructure.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Acquisition.Infrastructure.Migrations
{
    [DbContext(typeof(AcquisitionContext))]
    [Migration("20241005171706_add-maturities")]
    partial class addmaturities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Acquisition.Api.Domain.Entities.LoanApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoanOfferId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("LoanApplications");
                });

            modelBuilder.Entity("Acquisition.Api.Domain.Entities.LoanContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("LoanContracts");
                });

            modelBuilder.Entity("Acquisition.Api.Domain.Entities.LoanOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Maturity")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("LoanOffers");
                });

            modelBuilder.Entity("Acquisition.Api.Infrastructure.Persistence.Database.MaturityValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Maturities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = 6
                        },
                        new
                        {
                            Id = 2,
                            Value = 12
                        },
                        new
                        {
                            Id = 3,
                            Value = 24
                        },
                        new
                        {
                            Id = 4,
                            Value = 36
                        },
                        new
                        {
                            Id = 5,
                            Value = 48
                        },
                        new
                        {
                            Id = 6,
                            Value = 72
                        },
                        new
                        {
                            Id = 7,
                            Value = 84
                        });
                });

            modelBuilder.Entity("Acquisition.Api.Domain.Entities.LoanApplication", b =>
                {
                    b.OwnsOne("Acquisition.Api.Domain.ValueObjects.InitialLoanWish", "InitialLoanWish", b1 =>
                        {
                            b1.Property<Guid>("LoanApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<int>("Maturity")
                                .HasColumnType("integer");

                            b1.Property<string>("Project")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplications");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");
                        });

                    b.OwnsOne("Acquisition.Api.Domain.ValueObjects.UserInformation", "UserInformation", b1 =>
                        {
                            b1.Property<Guid>("LoanApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("LoanApplicationId");

                            b1.ToTable("LoanApplications");

                            b1.WithOwner()
                                .HasForeignKey("LoanApplicationId");
                        });

                    b.Navigation("InitialLoanWish");

                    b.Navigation("UserInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
