@Acquisition.Api_HostAddress = http://localhost:5064
@loanApplicationId = "aa8a746b-4875-4902-bcc9-50e8fbd11f57"

### Create Loan Application
POST http://localhost:5064/loan-application/create
Content-Type: application/json

{
   "loanApplicationId": {{loanApplicationId}}
}

### Select loan wish
POST http://localhost:5064/loan-application/select-loan-wish
Content-Type: application/json

{
  "loanApplicationId": {{loanApplicationId}},
  "project": "GreenProjectInvestment",
  "amount": 12000,
  "maturity": 12
}