name: Angular loan application journey

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    
    permissions:
      id-token: write
      contents: read

    env:
      ANGULAR_PATH: 'ConsumerCredit/Acquisition.WebApplication/acquisition.webapplication.angular.client'
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: |
          cd $ANGULAR_PATH
          npm install

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Replace API URL
        shell: pwsh
        run: |
          $environementFile = "$env:ANGULAR_PATH/src/environments/environment.prod.ts"
          (Get-Content $environementFile) -replace '{{AcquisitionBffUrl}}', '${{ secrets.ACQUISITION_BFF_URL }}' | Set-Content $environementFile

      - name: Build for production
        run: |
          cd $ANGULAR_PATH
          ng build --configuration=production

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: return await core.getIDToken()
          result-encoding: string

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_MOSS_024FAD803 }}
          action: "upload"
          app_location: ".$ANGULAR_PATH"
          api_location: ""
          output_location: "dist/acquisition.webapplication.angular.client"
          github_id_token: ${{ steps.idtoken.outputs.result }}
